### ISSUE TITLE
关于模型选择和参数设置的两点疑问

### ISSUE THREAD

**Issue by zhangxjohn** [yangjianxin1/Firefly#107]
你好，

1、为什么微调模型都选择Base而不是Chat版本呢？
2、为什么lr_scheduler_type选择constant_with_warmup而不是cos或者其他呢？

**Comment by yangjianxin1** [comment]
回复一：
1、如果有足够的数据和算力，建议在base模型上进行微调，因为你不确定官方chat版本的训练策略和数据是否符合你的使用场景。
2、如果你只有少量数据，例如上百上千条，考虑在chat版本上做指令微调，会更加经济实惠。
3、对base模型进行微调，数据组织格式更加自由，对chat模型做微调，需要遵循其原来的数据组织格式。

回复二：
lr_scheduler_type也可以用cosine，但没有做过实验。qlora官方用的constant，使用constant_with_warmup更多是遵循官方做法。
