### ISSUE TITLE
2b6模型损坏

### ISSUE THREAD

**Issue by xuguozhi** [yangjianxin1/Firefly#11]
Encountered 1 file(s) that may not have been copied correctly on Windows:
        pytorch_model.bin

**Comment by yangjianxin1** [comment]
请问现在可以正常下载吗 @xuguozhi

**Comment by xuguozhi** [comment]
> 请问现在可以正常下载吗 @xuguozhi
linux 还会报错 我是用git clone 下载的

**Comment by yangjianxin1** [comment]
尝试直接运行试试：model = BloomForCausalLM.from_pretrained('YeungNLP/firefly-2b6')，我也是linux，这种方式可以顺利下载。我晚点尝试一下使用别的方式下载，不行的话我再重新上传一份。

**Comment by xuguozhi** [comment]
手动下载了，没问题，写了个冒泡
