### ISSUE TITLE
checkpoint  resuming training

### ISSUE THREAD

**Issue by Orangeices** [yangjianxin1/Firefly#138]
请问是否可以支持断点继续训练？

**Comment by qyqyqy-art** [comment]
您好，我也有这个疑问。请问Firefly支持断点续训吗？

**Comment by Leawnn** [comment]
你好，我也有这个疑问，训练突然中断了：
![image](https://github.com/yangjianxin1/Firefly/assets/56593035/d3c7cc68-b4c6-4a2e-beb1-19b8bbc3bae9)

**Comment by Leawnn** [comment]
我这个断点继续训练是可行的
`# casts all the non int8 modules to full precision (fp32) for stability
    model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=training_args.gradient_checkpointing)

    if checkpoint_dir is not None:
        print("Loading adapters from checkpoint.")
        model = PeftModel.from_pretrained(model, checkpoint_dir, is_trainable=True)
    else:
        print(f'adding LoRA modules...')
        target_modules = find_all_linear_names(model)
        config = LoraConfig(
            r=args.lora_rank,
            lora_alpha=args.lora_alpha,
            target_modules=target_modules,
            lora_dropout=args.lora_dropout,
            bias="none",
            task_type="CAUSAL_LM",
        )
        model = get_peft_model(model, config)
    
    print(f'memory footprint of model: {model.get_memory_footprint()/(1024*1024*1024)} GB')`

**Comment by qy1026** [comment]
> 我这个断点继续训练是可行的 ` # casts all the non int8 modules to full precision (fp32) for stability model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=training_args.gradient_checkpointing)
> 
> ```
> if checkpoint_dir is not None:
>     print("Loading adapters from checkpoint.")
>     model = PeftModel.from_pretrained(model, checkpoint_dir, is_trainable=True)
> else:
>     print(f'adding LoRA modules...')
>     target_modules = find_all_linear_names(model)
>     config = LoraConfig(
>         r=args.lora_rank,
>         lora_alpha=args.lora_alpha,
>         target_modules=target_modules,
>         lora_dropout=args.lora_dropout,
>         bias="none",
>         task_type="CAUSAL_LM",
>     )
>     model = get_peft_model(model, config)
> 
> print(f'memory footprint of model: {model.get_memory_footprint()/(1024*1024*1024)} GB')
> ```
> 
> `

那请问，断点续训时的数据需要修改一下吗？我的意思是加载那些还没有训练的数据。

**Comment by qy1026** [comment]
> 我这个断点继续训练是可行的 ` # casts all the non int8 modules to full precision (fp32) for stability model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=training_args.gradient_checkpointing)
> 
> ```
> if checkpoint_dir is not None:
>     print("Loading adapters from checkpoint.")
>     model = PeftModel.from_pretrained(model, checkpoint_dir, is_trainable=True)
> else:
>     print(f'adding LoRA modules...')
>     target_modules = find_all_linear_names(model)
>     config = LoraConfig(
>         r=args.lora_rank,
>         lora_alpha=args.lora_alpha,
>         target_modules=target_modules,
>         lora_dropout=args.lora_dropout,
>         bias="none",
>         task_type="CAUSAL_LM",
>     )
>     model = get_peft_model(model, config)
> 
> print(f'memory footprint of model: {model.get_memory_footprint()/(1024*1024*1024)} GB')
> ```
> 
> `

这个确定是断点续训吗？

**Comment by Leawnn** [comment]
> > 我这个断点继续训练是可行的 ` # casts all the non int8 modules to full precision (fp32) for stability model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=training_args.gradient_checkpointing)
> > ```
> > if checkpoint_dir is not None:
> >     print("Loading adapters from checkpoint.")
> >     model = PeftModel.from_pretrained(model, checkpoint_dir, is_trainable=True)
> > else:
> >     print(f'adding LoRA modules...')
> >     target_modules = find_all_linear_names(model)
> >     config = LoraConfig(
> >         r=args.lora_rank,
> >         lora_alpha=args.lora_alpha,
> >         target_modules=target_modules,
> >         lora_dropout=args.lora_dropout,
> >         bias="none",
> >         task_type="CAUSAL_LM",
> >     )
> >     model = get_peft_model(model, config)
> > 
> > print(f'memory footprint of model: {model.get_memory_footprint()/(1024*1024*1024)} GB')
> > ```
> > 
> > 
> > `
> 
> 那请问，断点续训时的数据需要修改一下吗？我的意思是加载那些还没有训练的数据。
> 
> 这个确定是断点续训吗？是否还需要通过resume_from_checkpoint加载优化器状态？
你这么一说确实还有点问题，学习率也不是接续的....可以看下官方https://github.com/artidoro/qlora
看到说....
![image](https://github.com/yangjianxin1/Firefly/assets/56593035/9267c1b2-dbaa-43a6-a65c-712da4590789)

**Comment by Modas-Li** [comment]
全量参数微调，好像也不支持resume_from_checkpoint，
设置后还是从头开始训练。

**Comment by qy1026** [comment]
现在transformers已经支持断点续训了：https://github.com/huggingface/transformers/pull/24274
https://github.com/yangjianxin1/Firefly/blob/f1f8ca1b329019851108f52616e17c9a7d55d0eb/train_qlora.py#L209 is fixed.

**Comment by CrazyBoyM** [comment]
请求作者跟进更新，优化断点续训，ORPO、dataloader （针对大量数据增量预训练）等支持～
