### ISSUE TITLE
会有int4或者int8等量化、裁剪版本吗？

### ISSUE THREAD

**Issue by aoguai** [yangjianxin1/Firefly#15]
如题。
使用了一圈下来发现在中文语境下效果比同类惊艳很多。而且占用还很小！
但是在我实体机上跑得动，一到服务器就会爆内存被kill掉，感觉如果出了int4或者int8等量化、裁剪版本直接会赞爆了，哪怕效果低一点。

**Comment by wuwenjie1992** [comment]
## YeungNLP/firefly-2b6-v2 量化推理

* 最近我才关注到这个项目，我的方案如下
* 安装bitsandbytes
```
git clone https://github.com/timdettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x_nomatmul
python setup.py install
```
* load_in_4bit 
``` python

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

device = 'cuda'
model_id = "YeungNLP/firefly-2b6-v2"

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto", 
    load_in_4bit=True # 4 位精度加载模型
)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model.eval()

```

 ## 实测4 位精度加载模型，加载完毕时候大概占用2172MB的GPU显存，进行了几次交互后占用了2332MB的GPU显存。
`以上仅作参考` ，欢迎关注我[wuwenjie1992](https://github.com/wuwenjie1992)。

**Comment by aoguai** [comment]
> ## YeungNLP/firefly-2b6-v2 量化推理
> * 最近我才关注到这个项目，我的方案如下
> * 安装bitsandbytes
> 
> ```
> git clone https://github.com/timdettmers/bitsandbytes.git
> cd bitsandbytes
> CUDA_VERSION=117 make cuda11x_nomatmul
> python setup.py install
> ```
> 
> * load_in_4bit
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
> 
> device = 'cuda'
> model_id = "YeungNLP/firefly-2b6-v2"
> 
> model = AutoModelForCausalLM.from_pretrained(
>     model_id,
>     device_map="auto", 
>     load_in_4bit=True # 4 位精度加载模型
> )
> tokenizer = AutoTokenizer.from_pretrained(model_id)
> model.eval()
> ```
> 
> ## 实测4 位精度加载模型，加载完毕时候大概占用2172MB的GPU显存，进行了几次交互后占用了2332MB的GPU显存。
> `以上仅作参考` ，欢迎关注我[wuwenjie1992](https://github.com/wuwenjie1992)。

bitsandbytes 库目前仅在 Linux 发行版上受支持。目前不支持Windows。实际上我又希望在Windows上使用，也就是有量化好的模型能直接用就好了。不过还是十分感谢。

**Comment by mafamily2496** [comment]
> > ## YeungNLP/firefly-2b6-v2 量化推理
> > 
> > * 最近我才关注到这个项目，我的方案如下
> > * 安装bitsandbytes
> > 
> > ```
> > git clone https://github.com/timdettmers/bitsandbytes.git
> > cd bitsandbytes
> > CUDA_VERSION=117 make cuda11x_nomatmul
> > python setup.py install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * load_in_4bit
> > 
> > ```python
> > from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
> > 
> > device = 'cuda'
> > model_id = "YeungNLP/firefly-2b6-v2"
> > 
> > model = AutoModelForCausalLM.from_pretrained(
> >     model_id,
> >     device_map="auto", 
> >     load_in_4bit=True # 4 位精度加载模型
> > )
> > tokenizer = AutoTokenizer.from_pretrained(model_id)
> > model.eval()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## 实测4 位精度加载模型，加载完毕时候大概占用2172MB的GPU显存，进行了几次交互后占用了2332MB的GPU显存。
> > `以上仅作参考` ，欢迎关注我[wuwenjie1992](https://github.com/wuwenjie1992)。
> 
> bitsandbytes 库目前仅在 Linux 发行版上受支持。目前不支持Windows。实际上我又希望在Windows上使用，也就是有量化好的模型能直接用就好了。不过还是十分感谢。

有网友自己编译的windows版，可以用

**Comment by aoguai** [comment]
> > > ## YeungNLP/firefly-2b6-v2 量化推理
> > > 
> > > * 最近我才关注到这个项目，我的方案如下
> > > * 安装bitsandbytes
> > > 
> > > ```
> > > git clone https://github.com/timdettmers/bitsandbytes.git
> > > cd bitsandbytes
> > > CUDA_VERSION=117 make cuda11x_nomatmul
> > > python setup.py install
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > * load_in_4bit
> > > 
> > > ```python
> > > from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
> > > 
> > > device = 'cuda'
> > > model_id = "YeungNLP/firefly-2b6-v2"
> > > 
> > > model = AutoModelForCausalLM.from_pretrained(
> > >     model_id,
> > >     device_map="auto", 
> > >     load_in_4bit=True # 4 位精度加载模型
> > > )
> > > tokenizer = AutoTokenizer.from_pretrained(model_id)
> > > model.eval()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ## 实测4 位精度加载模型，加载完毕时候大概占用2172MB的GPU显存，进行了几次交互后占用了2332MB的GPU显存。
> > > `以上仅作参考` ，欢迎关注我[wuwenjie1992](https://github.com/wuwenjie1992)。
> > 
> > 
> > bitsandbytes 库目前仅在 Linux 发行版上受支持。目前不支持Windows。实际上我又希望在Windows上使用，也就是有量化好的模型能直接用就好了。不过还是十分感谢。
> 
> 有网友自己编译的windows版，可以用

确实，前阵子也发现了，但是一直没试验成功。不过感谢各位回复。我再研究研究吧
