### ISSUE TITLE
多卡一直报错，不支持int8 多卡吗？

### ISSUE THREAD

**Issue by kevinuserdd** [yangjianxin1/Firefly#18]
ValueError: You can't train a model that has been loaded in 8-bit precision on multiple devices

请问这是什么情况? 指定device_map = "auto"就会报这个错

**Comment by seafire1991** [comment]
device_map={"": 0}可以试试这样写

**Comment by yangjianxin1** [comment]
已更新代码，已经支持多卡并行4-bit进行训练

**Comment by xxllp** [comment]
这个怎么设置int8 训练的哈
