### ISSUE TITLE
请问要用qlora微调是这个命令嘛

### ISSUE THREAD

**Issue by Pobby321** [yangjianxin1/Firefly#22]
python train.py --train_args_file train_args/qlora.json

我看没用到train_qlora.py文件

**Comment by 2018211801** [comment]
顶顶~感觉是写错了吧

**Comment by yangjianxin1** [comment]
写错了启动脚本，更新了readme，应该是下面的脚本，目前建议只使用单卡：
```bash
CUDA_VISIBLE_DEVICES=0 python train_qlora.py --train_args_file train_args/qlora.json
```

**Comment by 2018211801** [comment]
> 写错了启动脚本，更新了readme，应该是下面的脚本，目前建议只使用单卡：
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 python train_qlora.py --train_args_file train_args/qlora.json
> ```



> 写错了启动脚本，更新了readme，应该是下面的脚本，目前建议只使用单卡：
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 python train_qlora.py --train_args_file train_args/qlora.json
> ```

怪不得我用多卡跑的时候报错Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:7!     可是我看用LORA的话就支持多卡运行呀，不知道QLORA时候时候能更新呢，如果问题解决了请up主踢我一下！谢谢呀！！

**Comment by 2018211801** [comment]
> 写错了启动脚本，更新了readme，应该是下面的脚本，目前建议只使用单卡：
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 python train_qlora.py --train_args_file train_args/qlora.json
> ```

我看见qlora里讨论说最新的accelerate已经解决这个问题了，up主快点更新呀！  因为我自己写的代码用多卡会报错Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:7! ，但是我的device_map是auto的，不知道是哪里出了问题呢

**Comment by yangjianxin1** [comment]
目前我也在修改这个bug，看了一些acclerate和qlora的官方实现和issue，把各种库都更新到了最新版本，在4*V100上运行还是会报错，还需要再看一下：
```
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 1756, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 1182, in prepare
    result = tuple(
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 1183, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 1022, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/accelerator.py", line 1258, in prepare_model
    raise ValueError(
ValueError: You can't train a model that has been loaded in 8-bit precision on a different device than the one you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device()}you're training on. Make sure you loaded the model on the correct device using for example `device_map={'':torch.cuda.current_device() or device_map={'':torch.xpu.current_device()}
```
@2018211801

**Comment by controZheng** [comment]
> 写错了启动脚本，更新了readme，应该是下面的脚本，目前建议只使用单卡：
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0 python train_qlora.py --train_args_file train_args/qlora.json
> ```

你好 方便建一个交流群吗

**Comment by yangjianxin1** [comment]
目前项目已经支持4-bit多卡并行训练

**Comment by yangjianxin1** [comment]
> > 写错了启动脚本，更新了readme，应该是下面的脚本，目前建议只使用单卡：
> > ```shell
> > CUDA_VISIBLE_DEVICES=0 python train_qlora.py --train_args_file train_args/qlora.json
> > ```
> 
> 你好 方便建一个交流群吗

感谢关注和支持，我们后续会考虑建立交流群

**Comment by 2018211801** [comment]
哇，感谢！！







                       
Original Email
                       
                     

Sender:"Yang JianXin"< ***@***.*** &gt;;

Sent Time:2023/6/21 0:19

To:"yangjianxin1/Firefly"< ***@***.*** &gt;;

Cc recipient:"xiao_cheng_zi"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [yangjianxin1/Firefly] 请问要用qlora微调是这个命令嘛 (Issue #22)




 
目前项目已经支持4-bit多卡并行训练

**Comment by zhangjunyi111** [comment]
@yangjianxin1 这个实现多卡量化的关键代码是哪里啊？能展示一下吗？
