### ISSUE TITLE
huggingface里面缺少config.json文件

### ISSUE THREAD

**Issue by createmomo** [yangjianxin1/Firefly#31]
```
OSError: YeungNLP/firefly-bloom-7b1-qlora-sft does not appear to have a file named config.json. Checkout 
'https://huggingface.co/YeungNLP/firefly-bloom-7b1-qlora-sft/main' for available files.
```

好像7b1的文件里面缺少config.json文件，不过理论上使用bloom-7b1原生的config也是可以的吧？

**Comment by yangjianxin1** [comment]
加载模型的时候应该是：
```python
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = 'bigscience/bloom-7b1'
adapter_name = 'YeungNLP/firefly-bloom-7b1-qlora-sft'
device = 'cuda'
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16,
    device_map='auto'
)
model = PeftModel.from_pretrained(model, adapter_name)
model.eval()
model = model.to(device)
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
```

**Comment by createmomo** [comment]
> 加载模型的时候应该是：
> 
> ```python
> from peft import PeftModel
> from transformers import AutoModelForCausalLM, AutoTokenizer
> import torch
> 
> model_name = 'bigscience/bloom-7b1'
> adapter_name = 'YeungNLP/firefly-bloom-7b1-qlora-sft'
> device = 'cuda'
> model = AutoModelForCausalLM.from_pretrained(
>     model_name,
>     trust_remote_code=True,
>     low_cpu_mem_usage=True,
>     torch_dtype=torch.float16,
>     device_map='auto'
> )
> model = PeftModel.from_pretrained(model, adapter_name)
> model.eval()
> model = model.to(device)
> tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
> ```

对，确实是。我应该是脑子短路了。忘记这是adapter部分的权重。谢谢提醒啦。
