### ISSUE TITLE
在v100上用qlora报OOM

### ISSUE THREAD

**Issue by NiHaoUCAS** [yangjianxin1/Firefly#33]
跑的是baichuan-7b模型，用的train_args/sft-qlora.json默认参数，只是替换了模型路径和数据路径。尝试使用1卡和8卡V100， 均报OOM。
‘’‘’
 return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)                                                                                  torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 250.00 MiB (GPU 1; 31.75 GiB total capacity; 30.35 GiB already allocated; 209.75 MiB free; 30.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF  
‘’‘’

**Comment by yangjianxin1** [comment]
建议把max_seq_length稍微调小一点点，比如900左右，应该就不会oom了。

**Comment by NiHaoUCAS** [comment]
把max_seq_length减小可以解决，谢谢！

**Comment by zhangjunyi111** [comment]
这个参数在哪个文件呢？
