### ISSUE TITLE
TypeError: GradientAccumulationPlugin.__init__() got an unexpected keyword argument 'sync_with_dataloader'

### ISSUE THREAD

**Issue by zxy333666** [yangjianxin1/Firefly#37]
/data/firefly/0625/Firefly/train_qlora.py:196 in <module>                                        │
│                                                                                                  │
│   193                                                                                            │
│   194                                                                                            │
│   195 if __name__ == "__main__":                                                                 │
│ ❱ 196 │   main()                                                                                 │
│   197                                                                                            │
│   198                                                                                            │
│   199                                                                                            │
│                                                                                                  │
│ /data/firefly/0625/Firefly/train_qlora.py:181 in main                                            │
│                                                                                                  │
│   178 │   # 进行一些配置和检查                                                                   │
│   179 │   args, training_args = setup_everything()                                               │
│   180 │   # 加载各种组件                                                                         │
│ ❱ 181 │   trainer = init_components(args, training_args)                                         │
│   182 │   # 开始训练                                                                             │
│   183 │   logger.info("*** starting training ***")                                               │
│   184 │   train_result = trainer.train()                                                         │
│                                                                                                  │
│ /data/firefly/0625/Firefly/train_qlora.py:166 in init_components                                 │
│                                                                                                  │
│   163 │   data_collator = SFTDataCollator(tokenizer, args.max_seq_length)                        │
│   164 │                                                                                          │
│   165 │   # 初始化Trainer                                                                        │
│ ❱ 166 │   trainer = LoRATrainer(                                                                 │
│   167 │   │   model=model,                                                                       │
│   168 │   │   args=training_args,                                                                │
│   169 │   │   train_dataset=train_dataset,                                                       │
│                                                                                                  │
│ /data/firefly/0625/Firefly/component/trainer.py:50 in __init__                                   │
│                                                                                                  │
│   47 │   │   │   preprocess_logits_for_metrics: Callable[[torch.Tensor, torch.Tensor], torch.    │
│   48 │   │   │   compute_loss=None,                                                              │
│   49 │   ):                                                                                      │
│ ❱ 50 │   │   super(Trainer, self).__init__(                                                      │
│   51 │   │   │   model=model,                                                                    │
│   52 │   │   │   args=args,                                                                      │
│   53 │   │   │   data_collator=data_collator,                                                    │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:335 in __init__                  │
│                                                                                                  │
│    332 │   │   self.deepspeed = None                                                             │
│    333 │   │   self.is_in_train = False                                                          │
│    334 │   │                                                                                     │
│ ❱  335 │   │   self.create_accelerator_and_postprocess()                                         │
│    336 │   │                                                                                     │
│    337 │   │   # memory metrics - must set up as early as possible                               │
│    338 │   │   self._memory_tracker = TrainerMemoryTracker(self.args.skip_memory_metrics)        │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:3830 in                          │
│ create_accelerator_and_postprocess                                                               │
│                                                                                                  │
│   3827 │   │   grad_acc_kwargs = {"num_steps": self.args.gradient_accumulation_steps}            │
│   3828 │   │   if version.parse(accelerate_version) > version.parse("0.20.3"):                   │
│   3829 │   │   │   grad_acc_kwargs["sync_with_dataloader"] = False                               │
│ ❱ 3830 │   │   gradient_accumulation_plugin = GradientAccumulationPlugin(**grad_acc_kwargs)      │
│   3831 │   │                                                                                     │
│   3832 │   │   # create accelerator object                                                       │
│   3833 │   │   self.accelerator = Accelerator(                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: GradientAccumulationPlugin.__init__() got an unexpected keyword argument 'sync_with_dataloader'

命令：torchrun --nproc_per_node=2 train_qlora.py --train_args_file train_args/bloom-sft-qlora.json

请教下大佬这个错误为什么？

**Comment by createmomo** [comment]
环境安装是按照up主的文件安装的嘛？

zxy333666 ***@***.***>于2023年6月25日 周日11:07写道：

**Comment by zxy333666** [comment]
是的，全是按照up主的环境装的

**Comment by zxy333666** [comment]
这是环境按照的版本：
peft                        0.4.0.dev0
accelerate                  0.21.0.dev0
transformers                4.31.0.dev0
bitsandbytes                0.39.0
loguru                      0.7.0
numpy                       1.21.4
pandas                      1.2.5
torch                       1.13.0
tensorboard                 2.13.0

**Comment by zxy333666** [comment]
可以了，更改了源码  /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:3830
