### ISSUE TITLE
多卡训练GPU使用有问题

### ISSUE THREAD

**Issue by clu2gt** [yangjianxin1/Firefly#38]
![image](https://github.com/yangjianxin1/Firefly/assets/118250087/6e8c4ee6-39c4-4f85-86cb-4b1e3e4f2040)
似乎多卡训练不是ddp?
多卡训练不是并行的？

**Comment by yangjianxin1** [comment]
由于qlora需要对base model进行量化，所以多卡训练使用的是Naive Pipeline Parallelism。详细可参考：
https://github.com/huggingface/accelerate/pull/1523

**Comment by yangjianxin1** [comment]
先close掉这个issue，如果有任何疑问，欢迎再次open。

**Comment by zhangjunyi111** [comment]
@clu2gt 你的训练启动代码能发一下吗？
