### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by deeplearningSprint** [yangjianxin1/Firefly#57]
│   194 │   # The reason we repeat same the comment below is that                                  │
│   195 │   # some Python versions print out the first line of a multi-line function               │
│   196 │   # calls in the traceback and some print out the last line                              │
│ ❱ 197 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   198 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   199 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   200                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

用Qlora finetune baichuan-13B-base的时候，出的这个问题，请问该如何解决？

谢谢！

**Comment by deeplearningSprint** [comment]
问题解决了，需要更新 modeling_baichuan.py 这个文件。

**Comment by yangjianxin1** [comment]
很赞👍🏻

**Comment by no-execution** [comment]
拉了最新的baichuan13b模型，还是有这个问题

**Comment by gzchenjiajun** [comment]
@deeplearningSprint 具体更新什么内容

**Comment by jx1100370217** [comment]
@deeplearningSprint 同问，具体更新什么内容，是怎么解决的
