### ISSUE TITLE
qlora微调baichuan-13b时报错

### ISSUE THREAD

**Issue by sexan** [yangjianxin1/Firefly#61]
Traceback (most recent call last):
  File "train_qlora.py", line 200, in <module>
    main()
  File "train_qlora.py", line 185, in main
    trainer = init_components(args, training_args)
  File "train_qlora.py", line 142, in init_components
    model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=training_args.gradient_checkpointing)
  File "/opt/conda/lib/python3.8/site-packages/peft/utils/other.py", line 86, in prepare_model_for_kbit_training
    model.enable_input_require_grads()
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1206, in enable_input_require_grads
    self._require_grads_hook = self.get_input_embeddings().register_forward_hook(make_inputs_require_grads)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1223, in get_input_embeddings
    return base_model.get_input_embeddings()
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1225, in get_input_embeddings
    raise NotImplementedError
NotImplementedError

按照github给出的requirement.txt搭建的环境，环境应该没问题，官方说已经支持baichuan-13b的qlora微调，但我这边运行仍报错，baichuan-7b是没问题的

**Comment by chenxiangzhen** [comment]
> Traceback (most recent call last): File "train_qlora.py", line 200, in main() File "train_qlora.py", line 185, in main trainer = init_components(args, training_args) File "train_qlora.py", line 142, in init_components model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=training_args.gradient_checkpointing) File "/opt/conda/lib/python3.8/site-packages/peft/utils/other.py", line 86, in prepare_model_for_kbit_training model.enable_input_require_grads() File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1206, in enable_input_require_grads self._require_grads_hook = self.get_input_embeddings().register_forward_hook(make_inputs_require_grads) File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1223, in get_input_embeddings return base_model.get_input_embeddings() File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1225, in get_input_embeddings raise NotImplementedError NotImplementedError
> 
> 按照github给出的requirement.txt搭建的环境，环境应该没问题，官方说已经支持baichuan-13b的qlora微调，但我这边运行仍报错，baichuan-7b是没问题的

您好，请问怎么解决的？

**Comment by sexan** [comment]
> > Traceback (most recent call last): File "train_qlora.py", line 200, in main() File "train_qlora.py", line 185, in main trainer = init_components(args, training_args) File "train_qlora.py", line 142, in init_components model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=training_args.gradient_checkpointing) File "/opt/conda/lib/python3.8/site-packages/peft/utils/other.py", line 86, in prepare_model_for_kbit_training model.enable_input_require_grads() File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1206, in enable_input_require_grads self._require_grads_hook = self.get_input_embeddings().register_forward_hook(make_inputs_require_grads) File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1223, in get_input_embeddings return base_model.get_input_embeddings() File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1225, in get_input_embeddings raise NotImplementedError NotImplementedError
> > 按照github给出的requirement.txt搭建的环境，环境应该没问题，官方说已经支持baichuan-13b的qlora微调，但我这边运行仍报错，baichuan-7b是没问题的
> 
> 您好，请问怎么解决的？

去hf拉取最新的模型文件
