### ISSUE TITLE
单机多卡推理报错

### ISSUE THREAD

**Issue by wangcyak** [yangjianxin1/Firefly#64]
是否支持单机多卡推理，能否给出一些修改意见

**Comment by xuguozhi** [comment]
[RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!](https://discuss.huggingface.co/t/runtimeerror-expected-all-tensors-to-be-on-the-same-device-but-found-at-least-two-devices-cuda-1-and-cuda-0/39548)

**Comment by wangcyak** [comment]
device = 'cuda'  修改为 device = 'cuda:0' 
 # 加载模型
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float16,
        device_map='auto'
    ).to(device).eval()   ---->  ).eval()  

   response = tokenizer.batch_decode(response_ids)   修改为  response = tokenizer.batch_decode(response_ids.cpu())

修改3处之后，可以多卡推理

**Comment by xuguozhi** [comment]
> device = 'cuda' 修改为 device = 'cuda:0'
> 
> # 加载模型
> ```
> model = AutoModelForCausalLM.from_pretrained(
>     model_name,
>     trust_remote_code=True,
>     low_cpu_mem_usage=True,
>     torch_dtype=torch.float16,
>     device_map='auto'
> ).to(device).eval()   ---->  ).eval()  
> ```
> 
> response = tokenizer.batch_decode(response_ids) 修改为 response = tokenizer.batch_decode(response_ids.cpu())
> 
> 修改3处之后，可以多卡推理
```model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16,
    device_map='auto'
).to(device).eval() `这句怎么改没看清楚
```
