### ISSUE TITLE
效果有点离谱啊 

### ISSUE THREAD

**Issue by jackaduma** [yangjianxin1/Firefly#7]
>>> text = input('User：')
User：床前明月光的下一句是什么
>>> text = '<s>{}</s></s>'.format(text)
>>> input_ids = tokenizer(text, return_tensors="pt").input_ids
>>> input_ids = input_ids.to(device)
>>> outputs = model.generate(input_ids, max_new_tokens=200, do_sample=True, top_p=0.85, temperature=0.35,
...                              repetition_penalty=1.2, eos_token_id=tokenizer.eos_token_id)
>>> rets = tokenizer.batch_decode(outputs)
>>> output = rets[0].strip().replace(text, "").replace('</s>', "")
>>> print("Firefly：{}".format(output))
Firefly：“你睡吧，我走了”
>>>

**Comment by xuguozhi** [comment]
`User：长风破浪会有时`
`Firefly：1、 网站建设的目地是让客户在访问你的站点时，能够更便捷快捷找到你要的信息内容。因此 ，网页页面设计方案要合乎检索模块的要求和习惯性，并尽可能减少对浏览者的危害。
2 、根据合理布局来提升用户体验度：一个好的网站应当具备优良的用户体会实际效果，并且必须考虑不一样种类的顾客要求；比如针对一些年纪较大的人而言，她们一般不容易去阅读文章比较长的內容；而对于年青人来讲则相反了，因而大家务必将信息内容的长度控制在一定的范畴内才可以吸引住到她们的留意力；另外还需考虑到的是，假如你给人的感觉很杂乱无章的话，那麼这种人群将会也会觉得你很差劲儿！
3 、提高商品或服务项目的品质：在互联网技术上开展营销推广的情况下一定要确保自身的商品和服务项目有非常高的质量水平才行，不然即便你在网上获得了大量的总流量也仅仅徒劳罢了；此外还要`

**Comment by yangjianxin1** [comment]
对数据和训练策略进行了优化，可以再尝试一下哈

**Comment by suwief** [comment]
请问解决了吗
