### ISSUE TITLE
关于Open LLM排行榜

### ISSUE THREAD

**Issue by llmrainer** [yangjianxin1/Firefly#70]
大佬，您好，感谢开源的项目代码及文档！
我看了这篇[文章](https://mp.weixin.qq.com/s/QG2YMo_QxaxS_Rr2yJrIeA)，
想问下，您的这个`Open LLM排行榜`得分是跑的哪个代码得到的？我也用了您的这个项目的代码尝试生成得到了一份模型，但是不知道训练的有效性。
我看榜单上有ARC、HellaSwag、MMLU及TruthfulQA几个项目，每个得分是如何评测的？可有相关的代码供学习使用。
感谢您的回答！

**Comment by yangjianxin1** [comment]
在huggingface上直接上传模型就可以自动测评了：
https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard
