### ISSUE TITLE
有没有办法用LoRA微调？

### ISSUE THREAD

**Issue by linkerlin** [yangjianxin1/Firefly#8]
如项目ReadMe说的，有时候效果会有偏差，是不是直接集成LoRA，方便最终使用者微调，会更加容易控制质量？
例如，我想拿Firefly来写一些文章，是不是可以拿我常看的内容方便的用LoRA微调下Firefly？

**Comment by yangjianxin1** [comment]
项目实现了QLoRA训练，比lora更高效，需要更少gpu，且效果也更好，可以尝试一下

**Comment by yangjianxin1** [comment]
后续项目会增加对lora的支持，不过还是比较建议使用qlora进行微调。
