### ISSUE TITLE
chatglm多轮对话微调方案

### ISSUE THREAD

**Issue by ShawnChang-ei** [yangjianxin1/Firefly#81]
您好，感谢分享
关于chatglm多轮对话数据集微调，官方给出的是一条多轮对话数据拆分成多条，感觉效率较低；
请问当前这种构造数据的方式支持chatglm嘛，causal with prefix似乎也不会有影响？

**Comment by yangjianxin1** [comment]
一条数据拆分成多条数据，效率是很低。
目前项目已经支持对chatglm2多轮对话微调了。

**Comment by ShawnChang-ei** [comment]
看到ChatGLM2SFTDataset中的构造格式,句首是否缺少了"[gMASK]"和"sop"
