### ISSUE TITLE
chatglm2微调失败，找不到lora需要的层

### ISSUE THREAD

**Issue by LDLINGLINGLING** [yangjianxin1/Firefly#86]
这里的lora层是找cls = bnb.nn.Linear4bit这个层，但是我运行chatglm2的代码，找不到这个层，最终导致peft找不到任何层进行高效微调

**Comment by Essence9999** [comment]
更新transformers到4.30.2试试

**Comment by yangjianxin1** [comment]
> 更新transformers到4.30.2试试

是的，transformers更新到4.30.2就可以，在项目的FAQ里也有提到。
