### ISSUE TITLE
firefly-llama2-13b和firefly-baichuan-13b谁的中文综合能力更强？

### ISSUE THREAD

**Issue by cristianohello** [yangjianxin1/Firefly#87]
firefly-llama2-13b和firefly-baichuan-13b谁的综合能力更强？
以及
firefly-llama2-13b和firefly-baichuan-13b谁的中文综合能力更强？

**Comment by yangjianxin1** [comment]
firefly-llama2-13b仅用了英文数据训练，所以中文能力不强。
firefly-baichuan-13b的中文能力更强。
